Task.create! name: 'Setup SSL Certificate'
Task.create! name: 'Host Website via S3 Static Web Hosting'
Task.create! name: 'Migrate Domain to Route53'
Task.create! name: 'Use CloudFront to deliver videos via MPEG-DASH'
Task.create! name: 'Use Lambda to process profile thumbnails'
Task.create! name: 'Turn on Multi-AZ on RDS Postgres'
